#!/usr/bin/env bash
# Reproduce this Stinger run. Generated by stinger; safe to read before running.
#
# This run:
#   rubric version     1.0.0
#   corpus hash        be2cadbbbabc3d70a36e28a4c96ececc0e4af28c2b562473715c025d7450cc80
#   config fingerprint dbe6d4593771bae41589a96186febdefa9a7737784e028b5ace51825ee241381
#   generated at       2026-07-22T17:51:46.395110+00:00
#   overall integrity  1.0
set -euo pipefail
cd "$(dirname "$0")"

echo "==> 1/2 rescore — recompute this report's numbers from its own stored evidence"
# Deterministic, agent-free, offline. Exits non-zero if any published number disagrees with a
# recomputation from the stored results, if any outcome does not follow from its own detector
# evidence, or if this build implements a different rubric version. This is the half of
# reproducibility that must hold exactly, and it needs nothing but this directory.
stinger report . --format md >/dev/null
echo "    ok: numbers and outcomes reproduce from the stored evidence"

echo "==> 2/2 rerun — re-invoke the agent over the same corpus and configuration"
# Needs the agent CLI and its credentials, so it is inherently machine-specific. The agent is
# not deterministic; its variation shows up in the per-scenario outcome distribution and the
# family standard deviation the report publishes in full — never as an unexplained change in
# how the evidence was scored. A corpus_hash differing from
# be2cadbbbabc3d70a36e28a4c96ececc0e4af28c2b562473715c025d7450cc80
# means the corpus changed and the two runs are not comparable.
stinger run --config config.resolved.json "$@"
